name: linter

on:
  push:
    branches:
      - dev
      - stage
      - main
  pull_request:
    branches:
      - dev
      - stage
      - main

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2
        with:
          php-version: '8.5'

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-progress --prefer-dist
          npm ci

      - name: Prepare Application
        run: |
          cp .env.example .env
          php artisan key:generate
          composer wayfinder

      - name: Run Pint
        run: composer lint:check

      - name: Check Frontend Format
        run: npm run format:check

      - name: Lint Frontend
        run: npm run lint:check

      - name: Type Check Frontend
        run: npm run types:check
